### ISSUE TITLE
How to use this action ? Please provide an example ?

### ISSUE THREAD

**Issue by SaitejaGurram** [falti/dotenv-action#20] opened 2021-08-10 12:58 UTC
Not at all clear

Step 1: I created a .env file and added some data
Step 2: In existing workflow i used this action try to log it out and it is throwing an error, checkout action is not there ?

Please provide a clear example with a demo repository ? 
Note : Don't know why people make actions and don't Provide example ? 

Hope you guys provide it with a good example. How to  use it

Thanks
Saiteja Gurram

**Comment by falti** [comment] 2021-08-11 06:29
Hi Sateja,
thank you for trying out this action.
As you did not link to your project or post the contents of your .env file and the exact error that you get it's difficult to understand what the problem is.
Please note that there is an example at the bottom of the README. It's pretty straight-forward.

Please provide more information about your scenario, otherwise I will close the issue.

Thanks
Frank

**Closed as completed** 2021-08-12 05:56 UTC
